name: glasses_assist
description: Blind-assist app (YOLOv8n + OCR + GPS + Voice) for iOS/Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.3
  vibration: ^1.7.7
  tflite_flutter: ^0.10.4
  google_mlkit_text_recognition: ^0.13.0
  image: ^4.1.7
  battery_plus: ^6.1.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/detector.tflite
    - assets/models/face.tflite
    - assets/models/labels.txt
    - assets/config/contexts.json
